name: Django CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "VENV=venv" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          . $VENV/bin/activate
          python -m pip install --upgrade pip
          pip install Django==5.2.4
          pip install -r requirements.txt
          pip install pylint bandit

      # Run Tests
      - name: Run Django tests
        run: |
          . $VENV/bin/activate
          python manage.py test

  linting:
    runs-on: ubuntu-latest
    needs: setup-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install Django==5.2.4
          pip install -r requirements.txt
          pip install pylint

      # Debug repository structure
      - name: Debug - Check repository structure
        run: |
          echo "=== Current directory contents ==="
          ls -la
          echo ""
          echo "=== Looking for Python files ==="
          find . -name "*.py" -type f | head -20
          echo ""
          echo "=== Checking for june25_classdemo2 directory ==="
          if [ -d "june25_classdemo2" ]; then
            echo "june25_classdemo2 directory found:"
            ls -la june25_classdemo2/
          else
            echo "june25_classdemo2 directory NOT found"
          fi
          echo ""
          echo "=== Looking for any Django apps ==="
          find . -name "apps.py" -o -name "models.py" -o -name "views.py" | head -10

      # Pylint with smart detection
      - name: Lint with pylint
        run: |
          . venv/bin/activate
          echo "Running pylint..."
          
          # Try different approaches to find what to lint
          if [ -d "june25_classdemo2" ] && [ "$(find june25_classdemo2 -name '*.py' | wc -l)" -gt 0 ]; then
            echo "Linting june25_classdemo2/ directory"
            pylint june25_classdemo2/
          elif [ -f "manage.py" ]; then
            echo "Django project detected, finding apps to lint"
            # Find Django apps (directories with models.py, views.py, or apps.py)
            APPS=$(find . -maxdepth 2 -name "models.py" -o -name "views.py" -o -name "apps.py" | xargs dirname | sort -u | grep -v "\./\." | head -5)
            if [ -n "$APPS" ]; then
              echo "Found Django apps: $APPS"
              echo "$APPS" | xargs pylint
            else
              echo "No Django apps found, linting manage.py"
              pylint manage.py
            fi
          else
            echo "No specific structure found, linting all Python files"
            find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*" | head -10 | xargs pylint || echo "Pylint completed with warnings"
          fi

  scanning:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install Django==5.2.4
          pip install -r requirements.txt
          pip install bandit

      # Scanning
      - name: Security scan with bandit
        run: |
          . venv/bin/activate
          echo "Running bandit security scan..."
          bandit -r june25_classdemo2/

  package:
    runs-on: ubuntu-latest
    needs: scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Package
      - name: Package the application
        run: |
          echo "Packaging project..."
          zip -r build.zip . -x '*.git*' '*venv*' '*.pyc' '*__pycache__*'

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: django-app-build
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: setup-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install Django==5.2.4
          pip install -r requirements.txt

      # Test again before deploy
      - name: Run tests before deploy
        run: |
          . venv/bin/activate
          python manage.py test

      # Refactory step (code cleanup/optimization)
      - name: Refactory - Code optimization
        run: |
          . venv/bin/activate
          echo "Running refactory optimizations..."
          # Add any code refactoring or optimization steps here
          python manage.py check --deploy

      # Deploy step
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
          # This could be deploying to a server, container registry, etc.